name: ublue-hyprland
base-image: ghcr.io/ublue-os/base-main
fedora-version: latest
description: Minimalistic ublue image, featuring Hyprland WM
scripts:
  pre:
    - add-kopia-repo.sh
    - remove-preinstalled-xwayland.sh
  post:
    - fix-tty1.sh
rpm:
  repos:
  - https://copr.fedorainfracloud.org/coprs/solopasha/hyprland/repo/fedora-%FEDORA_VERSION%/solopasha-hyprland-fedora-%FEDORA_VERSION%.repo
  - https://copr.fedorainfracloud.org/coprs/varlad/helix/repo/fedora-%FEDORA_VERSION%/varlad-helix-fedora-%FEDORA_VERSION%.repo
  - https://pkgs.tailscale.com/stable/fedora/tailscale.repo
  - https://copr.fedorainfracloud.org/coprs/dustee071/unstable-apps/repo/fedora-%FEDORA_VERSION%/dustee071-unstable-apps-fedora-%FEDORA_VERSION%.repo
  install:
    # desktop environment & dependencies & stuff
    - hyprland
    - waybar-hyprland
    - xdg-desktop-portal-hyprland
    - libnotify
    - dbus-tools
    - qt5-qtwayland
    - qt6-qtwayland
    - gtk-murrine-engine
    - python3-pip
    - libadwaita
    - libappindicator-gtk3
    - wlr-randr
    #- xorg-x11-server-Xwayland
    #- hyprpaper
    #- eww-wayland-git
    
    # authentication gui prompt
    - xfce-polkit

    # power control gui
    - wlogout

    # audio control gui
    - pavucontrol

    # night light
    - wlsunset

    # theming gui
    - nwg-look
    - qt5ct
    - qt6ct

    # monitor & workspace gui
    - nwg-displays

    # network gui
    - network-manager-applet

    # printing gui
    - system-config-printer

    # cron daemon
    - cronie
    
    # notification daemon
    - mako

    # screenshotting
    - grim
    - slurp
    # grimblast in usr/bin
    - swappy
    - wf-recorder

    # file manager
    - thunar
    - thunar-volman
    - thunar-archive-plugin
    # xplr in usr/bin
    - xarchiver

    # text editors
    - mousepad
    - helix

    # resource monitor
    - btop

    # video player
    - mpv
    - streamlink
    - wtwitch
    - yt-dlp

    # hotkey
    - keyd

    # image viewer
    - imv

    # tools & utils
    - gparted
    - liveusb-creator
    - wev
    # mimeo in usr/bin
    # handlr in usr/bin

    # clipboard
    #- copyq
    # cliphist in usr/bin
    # wl-clip-persist in usr/bin

    # vpn
    - tailscale

    # app launcher
    - wofi
    - fuzzel

    # terminal
    - kitty
    - alacritty
    - foot

    # shell
    - zsh

    # virtualization
    #- virt-install
    #- virt-manager
    #- virt-viewer
    #- libvirt-client
    #- libvirt-daemon-kvm

    # development
    #- dotnet-sdk-7.0

    # system info
    - neofetch

    # backup
    - kopia

    # fonts
    - overpass-fonts
    - overpass-mono-fonts
  remove:
    - firefox
    - firefox-langpacks
firstboot:
  yafti: false
  flatpaks:
    # permission editor for flatpaks
    - com.github.tchx84.Flatseal
    # firefox & codecs
    - org.mozilla.firefox
    - org.freedesktop.Platform.ffmpeg-full/x86_64/22.08
    # discord
    #- io.github.spacingbat3.webcord
    # gaming
    #- com.valvesoftware.Steam
    #- org.freedesktop.Platform.VulkanLayer.MangoHud
