# The image will be at ghcr.io/yourusername/name
name: ublue-hyprland
# The native container image to build on top of
# images. 
# Warning: Non-uBlue images might function unexpectly
base-container: ghcr.io/ublue-os/base-main
# What fedora version to use. Use an explicit version or `latest`.
# If you use `latest`, you will be automatically updated
# to the next major version assuming the image you're using as your base container
# builds with the tag (all uBlue images do this). 
fedora-version: 38
# This description will be visible in the container metadata
description: A starting point for further customization of uBlue images. Make your own! https://ublue.it/making-your-own/
# These rpms will be installed from the fedora repository
# using rpm-ostree and will be preinstalled in the final image
# https://src.fedoraproject.org/projects/rpms/*
# https://copr.fedorainfracloud.org/coprs/
rpms:
  - hyprland
  - waybar-hyprland
  - xdg-desktop-portal-hyprland
  - xorg-x11-server-Xwayland
  - xfce-polkit
  - libnotify
  - copyq
  - thunar
  - thunar-archive-plugin
  - thunar-volman
  - wlogout
  - btop
  - imv
  - zathura
  - qt5ct
  - neofetch
  - mpv
  - gparted
  - liveusb-creator
  - pavucontrol
  - wev
  - yt-dlp
  - discord
  - tailscale

  #text editor
  - helix

  #- dbus-tools

  #yafti deps
  - python3-pip
  - libadwaita

  #virtualisation
  #- virt-install
  #- virt-manager
  #- virt-viewer
  #- libvirt-client
  #- libvirt-daemon-kvm

  #screenshotting  
  - grim
  - slurp
  - swappy

  #pick one
  - dunst
  - mako
  #pick one
  - wofi
  - fuzzel
  #pick one
  - kitty
  - alacritty
  - foot
  #wezterm not in rpm

  
# These Flatpaks (from flathub) will be available for install on boot
# this is just an example selection.
# If you leave this empty you can use yafti for post-boot installation
flatpaks:
  - org.mozilla.firefox
  - org.freedesktop.Platform.ffmpeg-full
  #- com.discordapp.Discord #flatpak override --user --socket=wayland com.discordapp.Discord
  #- io.github.spacingbat3.webcord

